package org.flacro.po;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.flacro.po.Usernode;
import org.flacro.po.UsernodeExample;

public interface UsernodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    int countByExample(UsernodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    int deleteByExample(UsernodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    int insert(Usernode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    int insertSelective(Usernode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    List<Usernode> selectByExample(UsernodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    Usernode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    int updateByExampleSelective(@Param("record") Usernode record, @Param("example") UsernodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    int updateByExample(@Param("record") Usernode record, @Param("example") UsernodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    int updateByPrimaryKeySelective(Usernode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernode
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    int updateByPrimaryKey(Usernode record);
}