package org.flacro.po;

public class Usernode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usernode.id
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usernode.root
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    private Long root;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usernode.description
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usernode.userid
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usernode.pub
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    private Boolean pub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usernode.title
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usernode.id
     *
     * @return the value of usernode.id
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usernode.id
     *
     * @param id the value for usernode.id
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usernode.root
     *
     * @return the value of usernode.root
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public Long getRoot() {
        return root;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usernode.root
     *
     * @param root the value for usernode.root
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public void setRoot(Long root) {
        this.root = root;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usernode.description
     *
     * @return the value of usernode.description
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usernode.description
     *
     * @param description the value for usernode.description
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usernode.userid
     *
     * @return the value of usernode.userid
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usernode.userid
     *
     * @param userid the value for usernode.userid
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usernode.pub
     *
     * @return the value of usernode.pub
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public Boolean getPub() {
        return pub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usernode.pub
     *
     * @param pub the value for usernode.pub
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public void setPub(Boolean pub) {
        this.pub = pub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usernode.title
     *
     * @return the value of usernode.title
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usernode.title
     *
     * @param title the value for usernode.title
     *
     * @mbggenerated Thu Nov 17 15:22:30 CST 2011
     */
    public void setTitle(String title) {
        this.title = title;
    }
}